DROP DATABASE IF EXISTS rinx;
DROP USER IF EXISTS `rinxdev`@`%`;
DROP USER IF EXISTS `rinxadmin`@`%`;
CREATE DATABASE IF NOT EXISTS rinx CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `rinxadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'secret';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `rinx`.* TO `rinxadmin`@`%`;
CREATE USER IF NOT EXISTS `rinxdev`@`%` IDENTIFIED WITH mysql_native_password BY 'secret';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `rinx`.* TO `rinxdev`@`%`;
FLUSH PRIVILEGES;